### ISSUE TITLE
pybullet out of date in 

### ISSUE THREAD

**Issue by ThorAvaTahr** [axelbr/racecar_gym#11] opened 2022-12-26 20:11 UTC
doesn't work out of the box:

I get the following error
importerror numpy.core.multiarray failed to import

I am on windows using pycharm

fixed after updating pybullet to latest version

**Comment by axelbr** [comment] 2022-12-28 11:38
I just tried to do a fresh install with `pip install -e .` but I could not reproduce your error. Can you provide a set of commands that reproduce this error in a fresh python 3.10 virtual environment?

**Comment by axelbr** [comment] 2023-01-04 09:53
i will close this for now. feel free to reopen if this error persists.

**Closed as completed by axelbr** 2023-01-04 09:53 UTC
